version: "3.9"
services:
  api:
    container_name: projects-api
    build:
      context: ./PictuRAS
    ports:
      - "18018:18018"
    depends_on:
      - mongo
    links:
      - mongo
    environment:

      # AWS S3 configuration
      AWS_ACCESS_KEY_ID: ROOTNAME
      AWS_SECRET_ACCESS_KEY: CHANGEME123
      AWS_REGION: us-east-1
      AWS_S3_BUCKET_NAME: images


  mongo:
    container_name: mongo-server
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/database.json:/tmp/database.json
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
  