version: "3.9"
services:
  api:
    container_name: projects-api
    build:
      context: ./PictuRAS
    ports:
      - "80:18018"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo-server
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - ./data/database.json:/tmp/database.json
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
  