version: "2"
services:
 api:
  container_name: projetos-api
  image: ras/projetos-api
  ports:
    - "18018:18018"
  depends_on:
    - mongo
  links:
    - mongo
 mongo:
  container_name: mongo-server
  image: mongo
  ports:
    - "27017:27017"