services:
  rabbitmq:
    build: .
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ messaging port
      - "15672:15672" # Management UI port
    restart: unless-stopped
    volumes:
      - ./setup_queues.py:/setup_queues.py # Mount the setup script
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 30s
