services:
  frontend:
    build:
      context: ./pictuRAS-front
    ports:
      - "80:80"
    volumes:
      - ./pictuRAS-front:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
