services:
  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ messaging port
      - "15672:15672" # Management UI port
    restart: unless-stopped
    volumes:
      - ./rabbitmq/setup_queues.py:/setup_queues.py # Mount the setup script
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 30s

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # For MinIO API
      - "9001:9001"  # For MinIO Console
    volumes:
      - ~/minio/data:/data  # Mount the data directory
    environment:
      MINIO_ROOT_USER: ROOTNAME  # Set MinIO root user
      MINIO_ROOT_PASSWORD: CHANGEME123  # Set MinIO root password
    command: server /data --console-address ":9001"  # Start MinIO with console on port 9001
    restart: unless-stopped  # Automatically restart unless stopped manually

  brightness-tool-ms:
    image: gustominox/picturas_brightness_tool_ms:1.0
    container_name: brightness-tool-ms
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO 
    volumes:
      - ./images/src/:/images/src/
      - ./images/out/:/images/out/
    depends_on:
      rabbitmq:
        condition: service_healthy

  count-people-tool-ms:
    image: pinheiro2/picturas_count_people_tool_ms:latest
    container_name: brightness-tool-ms
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO 
    volumes:
      - ./images/src/:/images/src/
      - ./images/out/:/images/out/
    depends_on:
      rabbitmq:
        condition: service_healthy


  border-tool-ms:
    image: joaopedroabreu4/picturas_border_tool_ms:latest
    container_name: border-tool-ms
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO
    volumes:
      - ./images/src/:/images/src/
      - ./images/out/:/images/out/
    depends_on:
      rabbitmq:
        condition: service_healthy

  watermark-tool-ms:
    image: prcsousa/picturas-watermark-tool-ms:latest
    container_name: watermark-tool-ms
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PICTURAS_LOG_LEVEL=INFO 
    volumes:
      - ./images/src/:/images/src/
      - ./images/out/:/images/out/
    depends_on:
      rabbitmq:
        condition: service_healthy